name: GitHub deploy CI
run-name: ${{ github.actor }} deploying on GitHub 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  test1:
    uses: ./.github/workflows/ci.yml
  test2:
    uses: ./.github/workflows/playwright.yml
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - uses: actions/deploy-pages@v4

